repos:
  # See https://pre-commit.com for more information
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
      exclude: ^CHANGELOG.md
    - id: fix-byte-order-marker
    - id: mixed-line-ending
    - id: check-merge-conflict
    - id: check-case-conflict

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: helmlint

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.6.0
    hooks:
      - id: helm-docs

  - repo: local
    hooks:
    - id: generate-changelog
      name: generate-changelog
      entry: /usr/bin/make changelog
      language: script
      exclude: ^CHANGELOG.md

ci:
  skip:
    - helm-docs
