{
 "title": "Weblate",
 "tags": [ "weblate" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "query": {
     "query": "label_values(weblate_exporter_app_up, name)"
    }
   },
   {
    "name": "weblate_api_url",
    "query": {
     "query": "label_values(weblate_exporter_app_up, weblate_api_url)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weblate_exporter_app_up{weblate_api_url=\"$weblate_api_url\"}"
    }
   ]
  },
  {
   "title": "Configuration errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weblate_exporter_app_configuration_errors{weblate_api_url=\"$weblate_api_url\"}"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weblate_exporter_app_users{weblate_api_url=\"$weblate_api_url\"}"
    }
   ]
  },
  {
   "title": "Celery queues",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(weblate_exporter_app_celery_queues{weblate_api_url=\"$weblate_api_url\"})"
    }
   ]
  },
  {
   "title": "Projects",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weblate_exporter_app_projects{weblate_api_url=\"$weblate_api_url\"}"
    }
   ]
  },
  {
   "title": "Components",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weblate_exporter_app_components{weblate_api_url=\"$weblate_api_url\"}"
    }
   ]
  },
  {
   "title": "Languages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weblate_exporter_app_languages{weblate_api_url=\"$weblate_api_url\"}"
    }
   ]
  },
  {
   "title": "Translations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weblate_exporter_app_translations{weblate_api_url=\"$weblate_api_url\"}"
    }
   ]
  },
  {
   "title": "Celery queues length",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "weblate_exporter_app_celery_queues{weblate_api_url=\"$weblate_api_url\"}",
     "legendFormat": "{{weblate_celery_queue_name}} length"
    }
   ]
  },
  {
   "title": "Translation changes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "weblate_exporter_app_changes{weblate_api_url=\"$weblate_api_url\"}",
     "legendFormat": "Translation changes"
    }
   ]
  },
  {
   "title": "Translation units",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "weblate_exporter_app_units{weblate_api_url=\"$weblate_api_url\"}",
     "legendFormat": "Total number of units"
    },
    {
     "expr": "weblate_exporter_app_units_translated{weblate_api_url=\"$weblate_api_url\"}",
     "legendFormat": "Number of translated units"
    }
   ]
  },
  {
   "title": "Translation suggestions",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 22 },
   "targets": [
    {
     "expr": "weblate_exporter_app_suggestions{weblate_api_url=\"$weblate_api_url\"}",
     "legendFormat": "Number of pending suggestions"
    }
   ]
  }
 ]
}