apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weblate-exporter.fullname" . }}
  labels:
    {{- include "weblate-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "weblate-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "weblate-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "weblate-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "-m", "weblate_exporter", "-c", "/etc/weblate/weblate_exporter.yml"]
          # command: ["sleep", "3600"]
          ports:
            - name: http
              containerPort: {{ .Values.config.weblateExporterPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: WEBLATE_API_URL
            value: {{ .Values.config.weblateAPIUrl }}
          volumeMounts:
            - name: weblate-exporter-secrets
              mountPath: /etc/weblate
              readOnly: true
      volumes:
        - name: weblate-exporter-secrets
          secret:
            secretName: {{ include "weblate-exporter.fullname" . }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
