apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weblate-exporter.fullname" . }}
  labels:
    {{- include "weblate-exporter.labels" . | nindent 4 }}
type: Opaque

stringData:
  weblate_exporter.yml: |
    weblate_api_key: {{ .Values.config.weblateAPIKey }}
