{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "weblate-exporter.fullname" . }}
  labels:
    {{- include "weblate-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "weblate-exporter.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.serviceMonitor.port }}
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
      honorLabels: true
{{- end -}}
